### ISSUE TITLE
Responsive to window resize

### ISSUE THREAD

**Issue by sjjhsjjh** [AceCentre/FaceCommander#18]
Placeholder for checking how the user interface responds to the app window being resized, and making improvements if necessary.

**Comment by sjjhsjjh** [comment]
As part of this piece, maybe check all current references to the `fix_width` and `fix_height` config parameters.
https://github.com/search?q=repo%3AAceCentre%2FFaceCommander%20fix_width&type=code

**Comment by willwade** [comment]
also see #14 and #33 

I think this is related. These hover tips are next to useless. 

@alex5105 - I feel this needs a good think. We Deal with 
- Small screens that are tablets
- Largely touch as a interaction technique so hover boxes eg arent much use 

So it needs to all 
- Resize nicely
- Be easy to select dropdowns and panes. 

This is partly why @sjjhsjjh  was suggesting going to pages rather than dropdowns. Can you take a look?

<img width="532" alt="Screenshot 2024-08-29 at 12 22 33" src="https://github.com/user-attachments/assets/5f1887e1-2801-47b0-bba1-84c4fd6fe6dd">
