### ISSUE TITLE
Improvements to blink

### ISSUE THREAD

**Issue by willwade** [AceCentre/FaceCommander#22]
Great work @sjjhsjjh for implementing everything so far! 

As @gavinhenderson  and you mentioned in #2  there is I think a bit of wiggle room to improve blink maybe doing your own custom blink detection using landmarks. Definitley needs some playing with but maybe not much better than the inbuilt one..

But anyways heres some random thoughts

- The reason for me thinking of tweaking is the user cases where blinks are really subtle (like not fully shutting the eye) or eyes are really nearly closed to start with (we have seen this on Brain Injury units in hospitals..)
- I think we could do with a Blink L or R and Blink L & R - so two options somehow.. Not sure neatest way of doing that
- We do have some people who want to do an inverse "open eyes" for the action (I know it can sound niche - it is - but we do have some who are blind using this (I think Gavin might have mentioned this)

**Comment by gavinhenderson** [comment]
I think we need to implement a similar blink detection algorithm to the one we put together in EyeCommander. The current one just triggers as soon as we hit a threshold. Whilst this works its hard to setup for a user because if you go to low on the level it will trigger for involuntary blinks and too high will trigger for no blinks. Accuracy is very important in this sort of application.

The way we got around this was to add a timer in. 

So in EyeCommander, there are two sliders. One for 'gesture size', exactly like we have in FaceCommander. The other was a threshold time, which is the time that we have to be over the gesture size for before the action is triggered.

So for example if you set it to 1 second, you have to have you eyes closed for a second before it triggers. In reality users usually put it around 500ms, which although can slow down usage, we found the all users prefer 100% accuracy over speed.

Also it would be nice to have a both eyes blink rather than just 'wink' like we have at the minute
